mybatis:

  type-aliases-package: com.project.po             # 所有Entity别名类所在包
  config-location: classpath:mybatis/mybatis-config.xml  # mybatis配置文件所在路径        # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml    # mapper映射文件
  
spring: 
   datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver           # mysql驱动包
    url: jdbc:mysql://localhost:3306/shares?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true           # 数据库名称
    username: root
    password: 123456



        
        
    
      
  